-- Apensa consulta
SELECT ID_CAT_FACTS
      ,NR_VERSION
      ,DS_USER
      ,DS_TEXT_FACTS
      ,DT_LAST_UPDATE
      ,DT_SEND_DATE
      ,FG_DELETED
      ,DS_SOURCE
      ,DS_TYPE
      ,FG_STATUS_VERIFIED
      ,DS_STATUS_FEEDBACK
      ,NR_STATUS_SENTCOUNT
      ,DT_INSERTED
      ,DT_UPDATED
FROM DW_CATFACTS.TB_CAT_FACTS
wHERE DT_LAST_UPDATE BETWEEN '2020-08-01T00:00:01.000Z' AND '2020-08-31T00:00:01.000Z'


-- Cria tabela Stage com os dados de Agosto de 2020
CREATE TABLE IF NOT EXISTS 'DW_CATFACTS.STGCAT_FACTS_AGO_2020' (
SELECT ID_CAT_FACTS
      ,NR_VERSION
      ,DS_USER
      ,DS_TEXT_FACTS
      ,DT_LAST_UPDATE
      ,DT_SEND_DATE
      ,FG_DELETED
      ,DS_SOURCE
      ,DS_TYPE
      ,FG_STATUS_VERIFIED
      ,DS_STATUS_FEEDBACK
      ,NR_STATUS_SENTCOUNT
      ,DT_INSERTED
      ,DT_UPDATED
FROM DW_CATFACTS.TB_CAT_FACTS
wHERE DT_LAST_UPDATE BETWEEN '2020-08-01T00:00:01.000Z' AND '2020-08-31T00:00:01.000Z')